name: Flask CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest test_app.py

  SAST:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit Security Scan
        run: bandit -r . -f html -o bandit-report.html
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit-report.html

  DAST:
    runs-on: ubuntu-latest
    needs: SAST
    steps:
      - name: Pull ZAP Docker Image
        run: docker pull owasp/zap2docker
      - name: Start ZAP Docker Container
        run: |
          docker run -d --name zap -u zap -p 8080:8080 owasp/zap2docker zap.sh -daemon -host 0.0.0.0 -port 8080
      - name: Wait for ZAP to Start
        run: sleep 15
      - name: Run ZAP Active Scan
        run: |
          docker exec zap zap-cli quick-scan --self-contained --start-options "-config api.addrs.addr.name=.* -config api.addrs.addr.regex=true" http://your-app-url
      - name: Generate ZAP Report
        run: |
          docker exec zap zap-cli report -o zap-report.html -f html
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap-report.html
